src/harmonic/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from . import admin

urlpatterns = [
    url(r'^', include('pages.urls', namespace='pages')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^renderer/', include('renderer.urls', namespace='renderer')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

__author__ = 'rouk1'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^page/(?P<slug>[\w-]+)/$', views.page, name='page'),
]

src/catalog/models.py
from colorfield.fields import ColorField
from django.db import models
from harmonic.fields import MarkdownField
from harmonic.mixins import SeoModel


class Section(SeoModel):
    title = models.CharField(max_length=128)
    title_color = ColorField(default='#000000')
    background = models.ForeignKey(
        'renderer.MasterImage',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title


class Artist(models.Model):
    name = models.CharField(max_length=128)
    bio = MarkdownField()
    photo = models.ForeignKey(
        'renderer.MasterImage',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.name

class Album(SeoModel):
    is_published = models.BooleanField(default=False)
    title = models.CharField(max_length=128)
    reference = models.CharField(max_length=32)
    cover = models.ForeignKey(
        'renderer.MasterImage',
        related_name='catalog_album_cover'
    )
    sections = models.ManyToManyField('Section')
    artists = models.ManyToManyField('Artist')
    itunes_url = models.URLField()
    is_digital_release = models.BooleanField(default=False)
    description = MarkdownField()
    musicological_text = MarkdownField()
    instrument_name = models.CharField(max_length=255)
    instrument_text = MarkdownField()
    instrument_photo = models.ForeignKey(
        'renderer.MasterImage',
        related_name='catalog_album_instrument_photo',
        blank=True,
        null=True
    )
    track_list = MarkdownField()
    press_review = MarkdownField()

    def __str__(self):
        return '{} - {}'.format(self.reference, self.title)

src/legacy/models.py
class PersistentObject(object):
    '''an object that can be pickle'''

    prefix = 'default'

    def __init__(self, name, prefix):
        self.name = name
        self.prefix = prefix or PersistentObject.prefix


class Artist(PersistentObject):
    '''an artist that has recorded a disc in the pages'''

    prefix = 'artist'

    def __init__(self, name, prefix=None):
        super(Artist, self).__init__(name, Artist.prefix)


class Album(PersistentObject):
    '''an album off the pages'''

    prefix = 'album'

    def __init__(self, name, prefix=None):
        super(Album, self).__init__(name, Album.prefix)


class Section(PersistentObject):
    '''an section off the pages'''

    prefix = 'section'

    def __init__(self, name, prefix=None):
        super(Section, self).__init__(name, Section.prefix)


class Page(PersistentObject):
    '''an section off the pages'''

    prefix = 'site'

    def __init__(self, name, prefix=None):
        super(Page, self).__init__(name, Page.prefix)


class HomePage(Page):
    '''an section off the pages'''
    pass

src/pages/models.py
from django.db import models
from harmonic.fields import MarkdownField
from harmonic.mixins import SeoModel
from solo.models import SingletonModel


class DefaultBackground(SingletonModel):
    background = models.ForeignKey(
        'renderer.MasterImage',
        blank=True,
        null=True
    )


class Page(SeoModel):
    slug = models.SlugField()
    title = models.CharField(max_length=128)
    background = models.ForeignKey(
        'renderer.MasterImage',
        blank=True,
        null=True
    )
    content = MarkdownField()

    class Meta:
        verbose_name = 'simple page'
        verbose_name_plural = 'simple pages'

    def __unicode__(self):
        return 'Page: {}'.format(self.slug)


class HomePage(SeoModel, SingletonModel):
    content = MarkdownField()


class HomePagePush(models.Model):
    # FIXME add a published boolean
    # put them in the home page
    home_page = models.ForeignKey('HomePage')
    title = models.CharField(max_length=128)
    content = MarkdownField()

src/catalog/views.py
from django.shortcuts import render

# Create your views here.

src/pages/views.py
from catalog.models import Section
from pages.models import HomePage, HomePagePush, Page, DefaultBackground
from django.shortcuts import render, get_object_or_404


def home(request):
    p = HomePage.get_solo()
    items = []
    items.extend(Section.objects.all())
    items.extend(Page.objects.all())
    context = {
        'page': p,
        'background': DefaultBackground.get_solo().background,
        'pushes': HomePagePush.objects.all(),
        'items': items,
    }
    return render(request, 'pages/home.html', context)


def page(request, slug):
    p = get_object_or_404(Page, slug=slug)
    context = {
        'page': p,
        'background': (
            p.background if p.background is not None
            else DefaultBackground.get_solo().background
        ),
    }
    return render(request, 'pages/page.html', context)

src/templates/base_site.html
{% load staticfiles i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!doctype html>
<html
    lang="{{ LANGUAGE_CODE }}"
    style="{% block html_style %}{% endblock %}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static "css/styles.css" %}">
        <title>{% block head_title %}{{ page.title }}{% endblock %}</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <!--[if lt IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <header>
            <div class="logo">
                <a href="{% url 'pages:home' %}">
                    <span class="harmonic">HARMONIC</span>
                    <span class="classics">CLASSICS</span>
                </a>
            </div>
            <div class="nav">
                <nav></nav>
            </div>
        </header>

        <div class="container site-wrapper">
        {% block content %}
        {% endblock %}
        </div>

        {% block script %}
        <script src="{% static "js/landing.bundle.js" %}"></script>
        {% endblock %}

        {% if debug %}
        <!-- livereload -->
        <script>
        document.write(
            '<script src="http://'
            + (location.host || 'localhost').split(':')[0]
            + ':35729/livereload.js?snipver=1"></'
            + 'script>'
        );
        </script>
        <!-- livereload -->
        {% else %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-34010226-1', 'auto');
            ga('send', 'pageview');
        </script>
        {% endif %}
    </body>
</html>

src/templates/catalog/index.html
{% extends "base_site.html" %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static "css/styles.css" %}">
{% endblock %}

{% block script %}
<script src="{% static "js/landing.bundle.js" %}"></script>
{% endblock %}

src/templates/pages/home.html
{% extends "pages/page.html" %}
{% load staticfiles harmonic renderer %}

{% block head_title %}HARMONIC CLASSICS{% endblock %}

{% block content %}
<div class="home">
    <div class="lead">{{ page.content|markdown }}</div>
    {% for push in pushes %}
        <div class="push">{{ push.content|markdown }}</div>
    {% endfor %}
    <div class="items">
        <div class="row">
            {% for item in items %}
                <a
                    class="item page"
                    style="background-image: url('{% if item.background %}{% rendition_url item.background 0 300 %}{% else %}{% rendition_url background 0 300 %}{% endif %}');">
                    <div>{{ item.title }}</div>
                </a>
                {% if forloop.counter|divisibleby:3 or forloop.last %}
                    </div>
                    {% if not forloop.last %}
                        <div class="row">
                    {% endif %}
                {% endif %}
            {% endfor %}
    </div>
</div>
{% endblock %}

src/templates/pages/page.html
{% extends "base_site.html" %}
{% load staticfiles harmonic %}

{% block html_style %}
background: url({{ background.get_master_url }}) no-repeat center center fixed;
{% endblock %}

{% block head_title %}{{ page.title }}{% endblock %}

{% block head %}
<meta name="description" content="{{ page.seo_description }}"/>
<meta name="keywords" content="{{ page.seo_keywords }}"/>
{% endblock %}

{% block content %}
{{ page.content|markdown }}
{% endblock %}